# Generated by Django 3.0.2 on 2021-03-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='no_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='buscador.Empleado'),
        ),
    ]
