# Generated by Django 3.0.2 on 2021-06-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='no_control',
            field=models.CharField(max_length=8, verbose_name='Numero de Control'),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
