# Generated by Django 3.0.2 on 2021-06-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_auto_20210607_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido_M',
            new_name='apellido_m',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido_P',
            new_name='apellido_p',
        ),
    ]
